const API_BASE="";let token=localStorage.getItem("nova_token")||"",user=JSON.parse(localStorage.getItem("nova_user")||"null"),cart=[],shops=[];
const api=async(path,opt={})=>{opt.headers={"Content-Type":"application/json",...(opt.headers||{}),...(token?{Authorization:"Bearer "+token}:{})};let r=await fetch(API_BASE+path,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"حدث خطأ");return d};
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function home(){shops=await api("/api/shops");document.getElementById("app").innerHTML=`<header class="top"><div><div class="logo">🚀 توصيل نوفا</div><small>توصيل كل شيء إلى بابك</small></div><button class="ghost" onclick="authBox()">👤 ${user?esc(user.name):"دخول"}</button></header><main class="wrap"><section class="hero"><h2>وش تحتاج اليوم؟</h2><p>اختر متجرًا وأضف السلع إلى سلتك</p><button class="primary" onclick="locate()">📍 تحديد موقعي</button></section><div class="search"><input id="q" placeholder="ابحث عن متجر أو سلعة..." oninput="filterShops(this.value)"></div><h3>المتاجر</h3><div id="shops" class="grid"></div><h3>طلباتك</h3><div id="orders"></div></main><nav class="bottom"><button onclick="home()">⌂<small>الرئيسية</small></button><button onclick="cartBox()">🛒<small>السلة ${cart.length?`(${cart.length})`:""}</small></button><button onclick="orders()">📦<small>طلباتي</small></button></nav>`;renderShops(shops);if(user)orders()}
function renderShops(list){document.getElementById("shops").innerHTML=list.map(s=>`<article class="shop"><div style="font-size:45px">🏪</div><h3>${esc(s.name)}</h3><div class="muted">${esc(s.category)} · ${esc(s.eta)} · ${s.delivery_fee} ريال</div><button class="primary" style="width:100%;margin-top:10px" onclick="shopBox(${s.id})">عرض السلع</button></article>`).join("")}
function filterShops(q){let z=q.trim().toLowerCase();renderShops(shops.filter(s=>!z||s.name.toLowerCase().includes(z)||s.products.some(p=>p.name.toLowerCase().includes(z))))}
function locate(){navigator.geolocation?.getCurrentPosition(p=>alert(`تم تحديد موقعك\n${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`),()=>alert("اسمح للتطبيق باستخدام الموقع"))}
function shopBox(id){let s=shops.find(x=>x.id===id);modal(`<h2>🛍️ ${esc(s.name)}</h2>${s.products.map(p=>`<div class="item row"><div><b>${esc(p.name)}</b><div class="muted">${p.price} ريال</div></div><button class="primary" onclick="add(${s.id},${p.id})">إضافة</button></div>`).join("")}`)}
function add(shopId,productId){if(cart.length&&cart[0].shopId!==shopId){if(!confirm("السلة من متجر آخر، استبدالها؟"))return;cart=[]}let x=cart.find(x=>x.productId===productId);x?x.qty++:cart.push({shopId,productId,qty:1});close();alert("تمت الإضافة للسلة")}
function cartBox(){if(!cart.length)return modal("<h2>🛒 السلة فارغة</h2>");let s=shops.find(x=>x.id===cart[0].shopId),total=0;let html=cart.map(x=>{let p=s.products.find(p=>p.id===x.productId),sum=p.price*x.qty;total+=sum;return `<div class="item row"><span>${esc(p.name)} × ${x.qty}</span><b>${sum} ريال</b></div>`}).join("");modal(`<h2>🛒 السلة</h2>${html}<div class="card row"><b>الإجمالي</b><b>${total} ريال</b></div><button class="primary" style="width:100%" onclick="place(${s.id},${total})">تأكيد الطلب</button>`)}
async function place(shopId,total){if(!user)return authBox("سجّل الدخول أولاً لإتمام الطلب");let address=prompt("اكتب عنوان التوصيل");if(!address)return;try{let o=await api("/api/orders",{method:"POST",body:JSON.stringify({shop_id:shopId,items:cart.map(x=>({product_id:x.productId,quantity:x.qty})),address})});cart=[];close();alert("تم إنشاء الطلب #"+o.id);orders()}catch(e){alert(e.message)}}
async function orders(){if(!user)return;try{let os=await api("/api/orders");document.getElementById("orders").innerHTML=os.map(o=>`<div class="card"><div class="row"><b>طلب #${o.id}</b><span class="status ok">${esc(o.status)}</span></div><p>💰 ${o.total} ريال</p><p>📍 ${esc(o.address)}</p><button class="primary" onclick="orderBox(${o.id})">التفاصيل والتواصل</button></div>`).join("")||"<p class='muted'>لا توجد طلبات</p>"}catch(e){}}
async function orderBox(id){let o=await api("/api/orders/"+id);modal(`<h2>📦 طلب #${o.id}</h2><div class="card"><b>الحالة: ${esc(o.status)}</b><p>المتجر: ${esc(o.shop_name)}</p><p>العنوان: ${esc(o.address)}</p><p>الإجمالي: ${o.total} ريال</p>${o.driver_name?`<div class="item"><b>👤 المندوب: ${esc(o.driver_name)}</b><p>${esc(o.driver_phone||"")}</p><div class="actions"><a class="primary" href="tel:${o.driver_phone||""}">اتصال</a><a class="primary" href="https://wa.me/${(o.driver_phone||"").replace(/^0/,"966")}" target="_blank">واتساب</a></div></div>`:"<p class='muted'>لم يتم تعيين مندوب بعد.</p>"}</div>`)}
function authBox(msg=""){modal(`<h2>👤 ${user?"حسابك":"تسجيل الدخول"}</h2>${user?`<p>مرحباً ${esc(user.name)}</p><button class="primary" onclick="logout()">تسجيل الخروج</button>`:`<p class="muted">${msg}</p><input id="login" placeholder="البريد أو رقم الهاتف"><input id="pass" type="password" placeholder="كلمة المرور"><button class="primary" onclick="login()">دخول</button><hr><h3>حساب جديد</h3><input id="rn" placeholder="الاسم"><input id="rp" placeholder="رقم الهاتف"><input id="re" placeholder="البريد (اختياري)"><input id="rpass" type="password" placeholder="كلمة المرور"><button class="primary" onclick="register()">إنشاء حساب</button>`}`)}
async function login(){try{let d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({login:login.value,password:pass.value})});token=d.token;user=d.user;localStorage.setItem("nova_token",token);localStorage.setItem("nova_user",JSON.stringify(user));close();home()}catch(e){alert(e.message)}}
async function register(){try{let d=await api("/api/auth/register",{method:"POST",body:JSON.stringify({name:rn.value,phone:rp.value,email:re.value||null,password:rpass.value})});token=d.token;user=d.user;localStorage.setItem("nova_token",token);localStorage.setItem("nova_user",JSON.stringify(user));close();home()}catch(e){alert(e.message)}}
function logout(){token="";user=null;localStorage.clear();close();home()}
function modal(body){document.body.insertAdjacentHTML("beforeend",`<div id="m" class="modal" onclick="if(event.target.id==='m')close()"><section class="sheet"><button class="ghost" onclick="close()">×</button>${body}</section></div>`)}
function close(){document.getElementById("m")?.remove()}
const socket=io();socket.on("connect",()=>{if(token)socket.emit("auth",{token})});socket.on("order:update",()=>{if(user)orders()});
home();